(ns euroclojure.icons)
(def heart "\uD83D\uDC96")
(def heart-with-ribbon "\uD83D\uDC9D")
(def revolving-hearts "\uD83D\uDC9E")
(def cold-sweat "\uD83D\uDE30")
(def smirking "\uD83D\uDE0F")
(def expressionless "\uD83D\uDE11")
(def strong "\uD83D\uDCAA")
(def monorail "\uD83D\uDE9D")
(def computer "\uD83D\uDCBB")
(def screaming-in-fear "\uD83D\uDE31")
(def sweden "\uD83C\uDDF8\uD83C\uDDEA")
(def money-with-wings "\uD83D\uDCB8")
(def holding-hands-1 "\uD83D\uDC6C")
(def holding-hands-2 "\uD83D\uDC6B")
(def holding-hands-3 "\uD83D\uDC6D")
(def rocket "\uD83D\uDE80")
(def point-right "\uD83D\uDC49")
